In [3]:
#Create a directory names '/.kaggle'
!mkdir ~/.kaggle/

In [4]:
#copying the kaggle json file
!cp "/content/drive/MyDrive/kaggle API/kaggle.json" ~/.kaggle/kaggle.json

In [5]:
#set permission to the file
!chmod 600 ~/.kaggle/kaggle.json

In [6]:
#install the kaggle python package using pip
!python -m pip install -qq kaggle

In [7]:
#download the dataset from kaggle
!kaggle datasets download -d heesoo37/120-years-of-olympic-history-athletes-and-results

Downloading 120-years-of-olympic-history-athletes-and-results.zip to /content
  0% 0.00/5.43M [00:00<?, ?B/s]
100% 5.43M/5.43M [00:00<00:00, 64.6MB/s]

In [8]:
#unzip the dataset file
!unzip -qq "120-years-of-olympic-history-athletes-and-results"

In [9]:
import pandas as pd

In [10]:
data=pd.read_csv('/content/athlete_events.csv')

In [ ]:
data

In [11]:
#creating a dataframe
olympics = pd.DataFrame(data)

In [13]:
olympics

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [22]:
# Counting the distinct values in the 'games' column
total_games = olympics['Games'].nunique()

print("Total distinct games:", total_games)

Total distinct games: 51

In [ ]:
# Retrieving distinct values for 'year', 'season', and 'city' columns, ordered by 'year'
distinct_values = olympics[['Year', 'Season', 'City']].drop_duplicates().sort_values(by='Year')

print("Distinct values for year, season, and city:")
print(distinct_values)

In [20]:
data2=pd.read_csv('/content/noc_regions.csv')

In [23]:
o_region=pd.DataFrame(data2)

In [25]:
all_countries = pd.merge(olympics, o_region, on='NOC')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,602,Abudoureheman,M,22.0,182.0,75.0,China,CHN,2000 Summer,2000,Summer,Sydney,Boxing,Boxing Men's Middleweight,NaN,China,NaN
3,1463,Ai Linuer,M,25.0,160.0,62.0,China,CHN,2004 Summer,2004,Summer,Athina,Wrestling,"Wrestling Men's Lightweight, Greco-Roman",NaN,China,NaN
4,1464,Ai Yanhan,F,14.0,168.0,54.0,China,CHN,2016 Summer,2016,Summer,Rio de Janeiro,Swimming,Swimming Women's 200 metres Freestyle,NaN,China,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270762,120575,Mamorallo Tjoka,F,23.0,150.0,56.0,Lesotho,LES,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Marathon,NaN,Lesotho,NaN
270763,120575,Mamorallo Tjoka,F,27.0,150.0,56.0,Lesotho,LES,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Marathon,NaN,Lesotho,NaN
270764,122166,M'apotlaki Ts'elho,F,15.0,NaN,NaN,Lesotho,LES,1996 Summer,1996,Summer,Atlanta,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,Lesotho,NaN
270765,122215,Lefa Tsapi,M,23.0,170.0,63.0,Lesotho,LES,1984 Summer,1984,Summer,Los Angeles,Boxing,Boxing Men's Welterweight,NaN,Lesotho,NaN
270766,122299,Mosolesa Tsie,M,20.0,175.0,75.0,Lesotho,LES,2000 Summer,2000,Summer,Sydney,Boxing,Boxing Men's Welterweight,NaN,Lesotho,NaN

In [34]:
grouped_countries = all_countries.groupby(['Games', 'region']).size().reset_index(name='total_countries')

In [39]:
result = grouped_countries.groupby('Games')['total_countries'].count()

In [40]:
print(result)

Games
1896 Summer     12
1900 Summer     31
1904 Summer     14
1906 Summer     20
1908 Summer     22
1912 Summer     28
1920 Summer     29
1924 Summer     45
1924 Winter     19
1928 Summer     46
1928 Winter     25
1932 Summer     47
1932 Winter     17
1936 Summer     49
1936 Winter     28
1948 Summer     58
1948 Winter     28
1952 Summer     66
1952 Winter     30
1956 Summer     70
1956 Winter     32
1960 Summer     82
1960 Winter     30
1964 Summer     93
1964 Winter     36
1968 Summer    110
1968 Winter     36
1972 Summer    119
1972 Winter     34
1976 Summer     90
1976 Winter     36
1980 Summer     80
1980 Winter     36
1984 Summer    138
1984 Winter     48
1988 Summer    155
1988 Winter     56
1992 Summer    167
1992 Winter     64
1994 Winter     67
1996 Summer    195
1998 Winter     72
2000 Summer    198
2002 Winter     76
2004 Summer    199
2006 Winter     78
2008 Summer    201
2010 Winter     81
2012 Summer    202
2014 Winter     88
2016 Summer    203
Name: total_countries, dtype: int64